
== Accessing the BIG-IP


Once the Stacks are `CREATE_COMPLETE`, you can access the BIG-IPs through the Bastion Host and if you've provisioned the example application, optionally test the waf service:


* From Parent Template Outputs: 
** *Console*: Navigate to *CloudFormation > _STACK_NAME_ > Outputs*. 
** *AWS CLI*:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME}  --query  "Stacks[0].Outputs"
----
** Obtain the Private IP address of the BIG-IP Management Port:
*** *Console*: Navigate to *CloudFormation > _STACK_NAME_ > Outputs >
_bigipInstance01MgmtPrivateIp_*.
*** *AWS CLI*:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[ OutputKey=='bigipInstance01MgmtPrivateIp'].OutputValue" --output text
----
** Obtain the Public IP address of the bastion host: 
*** *Console*: *** *Console*: Navigate to *CloudFormation > _STACK_NAME_ > Outputs > _bastionHost_*.
*** *AWS CLI*:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[ OutputKey=='bastionHost'].OutputValue" --output text
----


=== SSH

From your desktop client/shell, create an SSH tunnel:
----
ssh -i [keyname-passed-to-template.pem] -o ProxyCommand='ssh -i [keyname-passed-to-template.pem] -W %h:%p ec2-user@[BASTION-HOST-PUBLIC-IP]' admin@[BIG-IP-MGMT-PRIVATE-IP]
----

Replace the variables in brackets before submitting the command.  For example:
----
ssh -i ~/.ssh/mykey.pem -o ProxyCommand=`ssh -i ~/.ssh/mykey.pem -W %h:%p ec2-user@34.82.102.190' admin@10.0.1.11
----


=== WebUI

Obtain the URL address of the BIG-IP Management Port.

* _NOTE_: Multi-NIC, will use https://host. Single NIC will use
https://host:8443.

. From your desktop client/shell, create an SSH tunnel through the Bastion Host:
+
----
ssh -i [keyname-passed-to-template.pem] ec2-user@[BASTION-HOST-PUBLIC-IP] -L [DESKTOP_PORT]:[BIG-IP-MGMT-PRIVATE-IP]:[BIGIP-GUI-PORT]
----
+
For example:
+
----
ssh -i ~/.ssh/mykey.pem ec2-user@34.82.102.190 -L 8443:10.0.1.11:443
----

. You should now be able to open a browser to the BIG-IP UI from your desktop:
+
https://localhost:8443

** _NOTE: By default, the BIG-IP system’s WebUI starts with a self-signed
cert. Follow your browser’s instructions for accepting self-signed certs
(for example, If using Firefox, click `Advanced` button, click
`Accept Risk and Continue`, if using Chrome, click inside the page and type this
`thisisunsafe`, etc.)_
** To Login:
*** username: *admin*
*** password: *YOUR_AWS_SECRET*


== Further Exploring


=== SSH

* From tmsh shell, type `bash` and enter to enter the bash shell.
** Examine the BIG-IP configuration file downloaded:
+
----
cat /config/cloud/runtime-init.conf
----
** Examine the running BIG-IP configurations:
*** The BIG-IP 
https://www.f5.com/pdf/products/automation-toolchain-overview.pdf[F5
Automation Toolchain] declarations:
+
[source,bash]
----
curl -su admin: http://localhost:8100/mgmt/shared/declarative-onboarding | jq .
curl -su admin: http://localhost:8100/mgmt/shared/appsvcs/declare | jq .
----
*** The BIG-IP https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud
Failover Extension (CFE)] declaration:
+
[source,bash]
----
curl -su admin: http://localhost:8100/mgmt/shared/cloud-failover/declare | jq . 
----

=== WebUI

* If you have provisioned the example application, navigate to *Virtual Services*.
** From the drop down menu *Partition* (upper right), select Partition =
`Tenant_1`.
** Navigate to *Local Traffic > Virtual Servers*. You should see the
Virtual Services (one for HTTP and one for HTTPS). This should show up
as Green. Click on them to look at the configuration _(declared in the
AS3 declaration)_.

** Navigate to *Security > Application Security*. Click on the policy named *CustomWAFPolicy* to inspect.


== Testing the WAF Service

If you have provisioned the example application, to test the WAF service, perform the following steps:

[arabic]
. Obtain the address of the WAF service:

* *Console*: Navigate to *CloudFormation > _STACK_NAME_ > Outputs >
_applicationPublicIp_*.
* *AWS CLI*:
+
----
aws --region ${REGION}  cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[?OutputKey=='applicationPublicIp'].OutputValue" --output text
----

[arabic, start=2]
. Verify the application is responding:

* Paste the IP address in a browser: `https://${IP_ADDRESS_FROM_OUTPUT}`
** _NOTE: By default, the Virtual Service starts with a self-signed
cert. Follow your browsers instructions for accepting self-signed certs
(for example, if using Chrome, click inside the page and type this
``thisisunsafe''. If using Firefox, click ``Advanced'' button, click
``Accept Risk and Continue'', etc.)._
* Use curl:
+
----
curl -sko /dev/null -w '%{response_code}\n' https://${IP_ADDRESS_FROM_OUTPUT}
----

[arabic, start=3]
. Verify the WAF is configured to block illegal requests:
+
----
curl -sk -X DELETE https://${IP_ADDRESS_FROM_OUTPUT}
----

* The response should include a message that the request was blocked,
and a reference support ID. Example:
+
----
$ curl -sko /dev/null -w '%{response_code}\n' https://55.55.55.55
200     
$ curl -sk -X DELETE https://55.55.55.55
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. 
Please consult with your administrator.<br><br>Your support ID is: 
2394594827598561347<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
----


== Testing Failover

If you have deployed the example application, to test failover, perform the following steps:

[arabic]
. Log on the BIG-IPs per instructions above:

* *Console*: Go to Device Management of Active Instance -> Traffic-Groups -> Select box next to *traffic-group-1* -> Click the "Force to Standby" button *.
* *BIG-IP CLI*:
+
----
tmsh run sys failover standby
----

[arabic, start=2]
. Verify the EIP associated w/ the Virtual Service (applicationPublicIp) is remapped to the peer BIG-IP (ex. from 10.0.10.11 in AZ1 to 10.0.20.11 in AZ2).


[arabic, start=2]
. Verify the application is responding:

* Paste the IP address in a browser: `https://${IP_ADDRESS_FROM_OUTPUT}`
** _NOTE: By default, the Virtual Service starts with a self-signed
cert. Follow your browsers instructions for accepting self-signed certs
(for example, if using Chrome, click inside the page and type this
``thisisunsafe''. If using Firefox, click ``Advanced'' button, click
``Accept Risk and Continue'', etc.)._
* Use curl:
+
----
curl -sko /dev/null -w '%{response_code}\n' https://${IP_ADDRESS_FROM_OUTPUT}
----

[arabic, start=3]
. Verify the WAF is configured to block illegal requests:
+
----
curl -sk -X DELETE https://${IP_ADDRESS_FROM_OUTPUT}
----

* NOTE: In this specific example, traffic is Source Address Translated and from the Example Application's perspective, the "Client" is the BIG-IP's addresses. The real client IP is passed via the `x-forwarded-for:` header. Observe how the "Client IP" changes from one BIG-IP in one AZ to the other. 



== Best practices for using {partner-product-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

// _Add any best practices for using the software._

For illustration purposes, this solution provides an option to pre-provision additional cloud resources (IP addresses)
needed for an example virtual service. However, in practice, this solution is only designed to facilitate the initial deployment as cloud-init runs once and is typically used for
initial provisioning, not as the primary configuration API for a
long-running platform. More typically in an infrastructure use case,
virtual services are added post initial deployment, outside the lifecycle of this Cloudformation Template and involves: 

1. *_Cloud_* - Provisioning additional IPs on the desired Network Interfaces.
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/MultipleIP.html#ManageMultipleIP[Assigning a Private IP]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-allocating[Allocating a Public IP]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-associating[Associating a Public IP] 
2. *_BIG-IP_* - Creating Virtual Services that match those
additional Secondary IPs. 
- Updating the https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/composing-a-declaration.html[AS3] declaration with additional Virtual Services.


_NOTE: For cloud resources, templates can be created or customized to pre-provision
and update addtional resources (for example, various combinations of
NICs, IPs, Public IPs, etc). Please see the link:#_support[Support Section]
for more information. For the BIG-IP configurations, you can leverage any
REST or Automation Tool Chain clients like
https://ansible.github.io/workshops/exercises/ansible_f5/3.0-as3-intro/[Ansible], https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_as3[Terraform],
etc._

== Deleting the Deployment

As Cloudformation does not delete S3 buckets that contain data, in order to delete this deployment, you will first need to manually empty and/or delete the S3 bucket created for the Cloud Failover Extension (provided via *cfeS3Bucket* parameter). Go to *AWS Management Console -> S3* and search for *cfeS3Bucket* bucket name, click the radio button associated with it and then click the "Empty" button. 

You can now delete the deployment. Go to *AWS Management Console -> Cloudformation -> Stacks* and select the radio button associated with the Parent Stack and then click the "Empty" button. 

For more information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^].



== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.


This solution requires Internet Access for:

[arabic]
. Downloading additional F5 software components used for onboarding and
configuring the BIG-IP (via GitHub.com). Internet access is required via
the management interface and then via a dataplane interface (for
example, external Self-IP) once a default route is configured. See
https://support.f5.com/csp/article/K13284[Overview of Mgmt Routing] for
more details. By default, as a convenience, this solution provisions
Public IPs to enable this but in a production environment, outbound
access should be provided by a `routed` SNAT service (for example, NAT
Gateway, custom firewall, etc). _NOTE: access via web proxy is not
currently supported. Other options include 1) hosting the file locally
and modifying the runtime-init package url and configuration files to
point to local URLs instead or 2) baking them into a custom image, using
the https://clouddocs.f5.com/cloud/public/v1/ve-image-gen_index.html[F5
Image Generation Tool]._
. Contacting native cloud services (for example, s3.amazonaws.com,
ec2.amazonaws.com, etc.) for various cloud integrations: **
_Onboarding_:
** https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime
Init] - to fetch secrets from native vault services ** _Operation_:
** https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/[F5
Application Services 3] - for features like Service Discovery
** https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/[F5
Telemetry Streaming] - for logging and reporting
** https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud
Failover Extension (CFE)] - for updating IP and route mappings
** Additional cloud services like
https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html[VPC
endpoints] can be used to address calls to native services traversing
the Internet. ** See link:#_security[Security] section for more details.

This CloudFormation template downloads helper code to configure the
BIG-IP system:

* f5-bigip-runtime-init.gz.run: The self-extracting installer for the F5
BIG-IP Runtime Init RPM can be verified against a SHA256 checksum
provided as a release asset on the F5 BIG-IP Runtime Init public GitHub
repository, for example:
https://github.com/F5Networks/f5-bigip-runtime-init/releases/download/1.3.2/f5-bigip-runtime-init-1.3.2-1.gz.run.sha256.
* F5 BIG-IP Runtime Init: The self-extracting installer script extracts,
verifies, and installs the F5 BIG-IP Runtime Init RPM package. Package
files are signed by F5 and automatically verified using GPG.
* F5 Automation Toolchain components: F5 BIG-IP Runtime Init downloads,
installs, and configures the F5 Automation Toolchain components.
Although it is optional, F5 recommends adding the extensionHash field to
each extension install operation in the configuration file. The presence
of this field triggers verification of the downloaded component package
checksum against the provided value. The checksum values are published
as release assets on each extension’s public GitHub repository, for
example:
https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.30.0/f5-appsvcs-3.30.0-5.noarch.rpm.sha256

The following configuration file will verify the Declarative Onboarding
and Application Services extensions before configuring AS3 from a local
file:

[source,yaml]
----
runtime_parameters: []
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.23.0
          extensionHash: bfe88c7cf3fdb24adc4070590c27488e203351fc808d57ae6bbb79b615d66d27
        - extensionType: as3
          extensionVersion: 3.30.0
          extensionHash: 47cc7bb6962caf356716e7596448336302d1d977715b6147a74a142dc43b391b
extension_services:
    service_operations:
      - extensionType: as3
        type: url
        value: file:///examples/declarations/as3.json
----

More information about F5 BIG-IP Runtime Init and additional examples
can be found in the
https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/README.md[GitHub
repository].


This template can send non-identifiable statistical information to F5 Networks to help us improve our templates. You can disable this functionality by setting the **autoPhonehome** system class property value to false in the F5 Declarative Onboarding declaration. See Customizing the BIG-IP Configuration section for additional information.

List of endpoints BIG-IP may contact during onboarding: 

* BIG-IP image default: 
** vector2.brightcloud.com (by BIG-IP image for
https://support.f5.com/csp/article/K03011490[IPI subscription
validation] )

* Solution / Onboarding:
** github.com (for downloading helper packages mentioned above)
** f5-cft.s3.amazonaws.com (downloading GPG Key and other helper configuration files)
** license.f5.com (licensing functions)

* Telemetry:

** product-s.apis.f5.com.
** f5-prod-webdev-prod.apigee.net.
** id-prod-global-endpoint.trafficmanager.net.
** global.azure-devices-provisioning.net.
** www-google-analytics.l.google.com


== Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

//_Add any other details that will help the customer use the software on AWS._

Reference Links:

- https://www.f5.com/[F5 website].
- https://aws.amazon.com/marketplace/pp/prodview-v2lgyijcawiti[F5 BIG-IP Virtual Edition - BEST (PAYG, 25Mbps)]
- https://aws.amazon.com/marketplace/pp/prodview-73utu5c5sfyyc[F5 BIG-IP VE - ALL (BYOL, 2 Boot Locations)]
- https://www.f5.com/products/big-ip-services/local-traffic-manager[Local Traffic Manager (LTM)]
- https://www.f5.com/products/security/advanced-waf[Application Security Manager (ASM)]
- https://aws.amazon.com/marketplace/pp/prodview-cs4qijwjf3ijs[F5 Advanced WAF with LTM, IPI, and Threat Campaigns (PAYG, 25Mbps)]
- https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init] - to fetch secrets from cloud vault services
- https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[F5 Cloud Failover Extension (CFE)] -> for updating cloud resources (IP and route mappings)
- https://www.f5.com/pdf/products/automation-toolchain-overview.pdf[ F5 Automation Tool Chain]
*  https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/[F5 Declarative Onboarding (DO)] -> for system onboarding
*  https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/[F5 Application Services 3 (AS3)] -> declarative virtual service definitions
*  https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/[F5 Telemetry Streaming (TS)] -> for logging and reporting (not deployed by default in this solution )
* https://github.com/f5devcentral/f5-demo-httpd[Example Application (nginx)]
