
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited


=== Customizing the BIG-IP configuration

Before deploying, you first need to confirm or customize the desired BIG-IP Configuration. The initial BIG-IP configurations are passed through the https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init] config files. As the potential amount of customization for the BIG-IP configuration is so large, these are the primary mechanisms to customize the initial BIG-IP configurations for your deployment. Customizing the BIG-IP configurations generally involves updating AND rehosting these files and passing their location through the *bigIpRuntimeInitConfig* template parameters.

By default, per the diagram above, this solution deploys a minimal 2NIC PAYG configuration into the default Quickstart network topology using the following configuration files in the
`/declarations` folder in this repository:

** `runtime-init-conf-2nic-payg-instance01.yaml`
** `runtime-init-conf-2nic-payg-instance02.yaml`

This deploys a minimal baseline HA failover cluster *without* any virtual services provisioned.

Optionally, to illustrate how services work, you can deploy an _example_ waf protected web service ( which will deploy web application instances and a waf protected virtual service on the BIG-IPs). To do this, set *provisionExampleApp* parameter to *true* and reference the following configuration files via *bigIpRuntimeInitConfig* parameters instead.

** `runtime-init-conf-2nic-payg-instance01-with-app.yaml`
** `runtime-init-conf-2nic-payg-instance02-with-app.yaml`


Any further customizations require *updating* AND *rehosting* your configuration files at a *custom* URL.  

NOTE: *IMPORTANT* If hosting on git, any URLs pointing to git *must* use the raw file format
(for example, `raw.githubusercontent.com`).


The BIG-IP configurations must match the external environment in which they are deployed. Although the provided Runtime-Init config examples extract and templatize many common values, some values are still harcoded and need to be updated to match your specific environment or deployment first. 


==== Common Example Customization 1


For example, to deploy a *Bring Your Own License (BYOL)* instance:

[arabic]
. Edit/modify the Declarative Onboarding (DO) declaration in a
corresponding example `byol` runtime-init config file with the new `regKey`
value.

Example snippet:

From:
[source,yaml]
----
...
          My_License:
            class: License
            licenseType: regKey
            regKey: REPLACE_WITH_VALID_REGKEY
...
----

To:
[source,yaml]
----
...
          My_License:
            class: License
            licenseType: regKey
            regKey: AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE
...
----

[arabic, start=2]
. Publish/host the customized runtime-init config file at a location
reachable by the BIG-IP at deploy time (for example: git, S3, etc.).
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.
. Update the *bigIpImageId* input parameter to a valid byol image ID.

{empty} +

==== Common Example Customization 2

For example, if you would like to change hostnames, disable usage reporting to F5, ntp / dns servers, etc. :

[arabic]
. Edit/modify the Declarative Onboarding (DO) declaration in a
corresponding example runtime-init configs file with your new
values.

Example snippet:

From:
[source,yaml]
----
...
          My_System:
            autoPhonehome: true
            class: System
            hostname: "failover01.local"
...
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - failover01.local
              - failover02.local
...
----

To:
[source,yaml]
----
...
          My_System:
            autoPhonehome: false
            class: System
            hostname: "bigip-cluster-01-a.yourcompany.com"
...
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - bigip-cluster-01-a.yourcompany.com
              - bigip-cluster-01-b.yourcompany.com
...
----


[arabic, start=2]
. Publish/host the customized runtime-init config files at a location
reachable by the BIG-IP at deploy time (for example: git, S3, etc.).
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.

{empty} +

==== Common Example Customization 3 

For example, if deploying into an *existing* network, it will certainly have different network topologies, subnetting, etc.:

[arabic]
. Edit/modify the Declarative Onboarding (DO) declaration in a
corresponding example runtime-init configs file with your new
values.

Example snippet:

[source,yaml]
----
...
          trust:
            class: DeviceTrust
            localUsername: admin
            localPassword: '{{{BIGIP_PASSWORD}}}'
            remoteHost: <YOUR-NEW-HA-PEER-IP-HERE>
...
----

NOTE: The *remoteHost* attribute is only used in one of the peer's configs (with `02` in the name). This should correspond the the value you pass for BIG-IP 01's Management IP. 

[arabic, start=2]
. Publish/host the customized runtime-init config files at a location
reachable by the BIG-IP at deploy time (for example: git, S3, etc.).
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.

{empty} +
{empty} +


TIP: For additional information and examples, see https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP
Runtime Init].

{empty} +
{empty} +