// Include details about the license and how they can sign up. If no license is required, clarify that.

// Or, if the deployment uses an AMI, update this paragraph. If it doesn’t, remove the paragraph.
The Quick Start requires a subscription to the Amazon Machine Image (AMI) for {partner-product-name}, which is available from https://aws.amazon.com/marketplace/[AWS Marketplace].

By default, this Quick Start deploys https://aws.amazon.com/marketplace/pp/prodview-v2lgyijcawiti[F5 BIG-IP Virtual Edition - BEST (PAYG, 25Mbps)] instances.

If you would like to deploy other types of BIG-IP instances, accept the terms for the desired offering and obtain the AMI ID for that offering. For example, to get the list of BIG-IP AMI IDs in us-east-1.


[source,yaml]
----
aws ec2 describe-images --filters 'Name=name,Values=*BIGIP*' --query 'Images[*].[ImageId,Name]' --region us-east-1
----


You can pass the desired AMI ID to the template's *bigIpImageId* parameter.

If deploying to production, you may want to leverage Bring Your Own License (BYOL) instances, for example https://aws.amazon.com/marketplace/pp/prodview-73utu5c5sfyyc[F5 BIG-IP VE - ALL (BYOL, 2 Boot Locations)], and will also need registration keys. If you do not have a registration keys, keys can be obtained via F5's https://www.f5.com/trials/big-ip-virtual-edition[website]. Additional pricing, terms, and conditions may apply. For instructions on customizing the deployment to use a BYOL image, see
