// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== Customize the {partner-product-short-name} configuration

If needed, customize the {partner-product-short-name} configuration. The initial {partner-product-short-name} configurations are passed through the https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init^] configuration files. As the potential amount of customization for the {partner-product-short-name} configuration is so large, these files are the primary mechanisms to customize the initial {partner-product-short-name} configurations for your deployment. Customizing the {partner-product-short-name} configurations generally involves updating and rehosting these files and passing their location through the *bigIpRuntimeInitConfig* template parameters.

By default, the Quick Start deploys a minimal 2NIC PAYG configuration into the default Quick Start network topology using the following configuration files in the
`/declarations` folder:

** `runtime-init-conf-2nic-payg-instance01.yaml`
** `runtime-init-conf-2nic-payg-instance02.yaml`

A minimal baseline high availability (HA) failover cluster *without* any virtual services provisioned is deployed.

Optionally, to illustrate how services work, you can deploy an example web application firewall (WAF)-protected web service (which deploys web application instances and a WAF-protected virtual service on the {partner-product-short-name} instances. To do this, set the *provisionExampleApp* parameter to *true* and reference the following configuration files via *bigIpRuntimeInitConfig* parameters instead.

** `runtime-init-conf-2nic-payg-instance01-with-app.yaml`
** `runtime-init-conf-2nic-payg-instance02-with-app.yaml`

If your deployment requires additional customizations, update and rehost your configuration files at a custom URL.

NOTE: *IMPORTANT* If hosting on GitHub, URLs that point to GitHub must use the raw file format
(for example, `raw.githubusercontent.com`).


The {partner-product-short-name} configurations must match the external environment in which they are deployed. Although the provided Runtime-Init configuration examples extract and templatize many common values, some values are still hardcoded and must be updated to match your specific environment or deployment first.


==== Common customization example 1

To deploy a Bring Your Own License (BYOL) instance, perform these steps:

[arabic]
. Edit/modify the Declarative Onboarding (DO) declaration in a
corresponding example `byol` runtime-init configuration file with the new `regKey`
value.

Example snippet:

From:
[source,yaml]
----
...
          My_License:
            class: License
            licenseType: regKey
            regKey: REPLACE_WITH_VALID_REGKEY
...
----

To:
[source,yaml]
----
...
          My_License:
            class: License
            licenseType: regKey
            regKey: AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE
...
----

[arabic, start=2]
. Publish or host the customized `runtime-init` configuration file at a location
that can be accessed by {partner-product-short-name} at deployment time (for example, git, S3, etc.).
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.
. Update the *bigIpImageId* input parameter to a valid BYOL image ID.

{empty} +

==== Common customization example 2

If you want to change host names, perform these steps to disable usage reporting to the {partner-product-short-name} NTP and DNS servers, etc.:

[arabic]
. Edit or modify the DO declaration in a
corresponding example `runtime-init` configuration file with the new
values.

Example snippet:

From:
[source,yaml]
----
...
          My_System:
            autoPhonehome: true
            class: System
            hostname: "failover01.local"
...
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - failover01.local
              - failover02.local
...
----

To:
[source,yaml]
----
...
          My_System:
            autoPhonehome: false
            class: System
            hostname: "bigip-cluster-01-a.yourcompany.com"
...
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - bigip-cluster-01-a.yourcompany.com
              - bigip-cluster-01-b.yourcompany.com
...
----


[arabic, start=2]
. Publish or host the customized `runtime-init` configuration files at a location
that can be accessed by {partner-product-short-name} at deployment time (for example, git, S3, etc.)
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.

{empty} +
{empty} +


TIP: For additional information and examples, refer to the https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init^] GitHub repository.

{empty} +
{empty} +
