// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== Customize the {partner-product-short-name} configuration

If needed, customize the {partner-product-short-name} configuration. The initial {partner-product-short-name} configurations are passed through the https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init^] configuration files. These files are the primary mechanisms to customize the initial {partner-product-short-name} configurations for your deployment. They also allow for large amounts of {partner-product-short-name} customizations. Customizing the {partner-product-short-name} configurations generally involves updating and rehosting these files and passing their location through the *bigIpRuntimeInitConfig* template parameters.

By default, the Quick Start deploys a minimal 2NIC PAYG configuration into the default Quick Start network topology using the following configuration files in the `/declarations` folder:

** `runtime-init-conf-2nic-payg-instance01.yaml`
** `runtime-init-conf-2nic-payg-instance02.yaml`

A minimal baseline high availability (HA) failover cluster is deployed. No virtual services are provisioned.

Optionally, you can deploy an example web application firewall (WAF)-protected web service to illustrate how services work. The example application deploys web application instances and a WAF-protected virtual service on the {partner-product-short-name} instances. To deploy the example application, set the *provisionExampleApp* parameter to *true* and reference the following configuration files via *bigIpRuntimeInitConfig* parameters:

** `runtime-init-conf-2nic-payg-instance01-with-app.yaml`
** `runtime-init-conf-2nic-payg-instance02-with-app.yaml`

If your deployment requires additional customizations, update and rehost your configuration files at a custom URL.

NOTE: *IMPORTANT* If hosting on GitHub, URLs that point to GitHub must use the raw file format (for example, `raw.githubusercontent.com`).

The {partner-product-short-name} configurations must match the external environment in which they are deployed. Although the provided Runtime-Init configuration examples extract and templatize many common values, some values are still hardcoded and must be updated to match your specific environment or deployment first.

==== Common customization example 1

To deploy a Bring Your Own License (BYOL) instance, perform these steps:

[arabic]
. Edit or modify the Declarative Onboarding (DO) declaration in a
corresponding example `byol` runtime-init configuration file with the new `regKey`
value.

Example snippet:

From:
[source,yaml]
----
...
          My_License:
            class: License
            licenseType: regKey
            regKey: REPLACE_WITH_VALID_REGKEY
...
----

To:
[source,yaml]
----
...
          My_License:
            class: License
            licenseType: regKey
            regKey: AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE
...
----

[arabic, start=2]
. Publish or host the customized `runtime-init` configuration file at a location
that can be accessed by {partner-product-short-name} at deployment time (for example, git, S3, etc.).
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.
. Update the *bigIpImageId* input parameter to a valid BYOL image ID.

{empty} +

==== Common customization example 2

If you want to change host names, perform these steps to disable usage reporting to the {partner-product-short-name} NTP and DNS servers, etc.:

[arabic]
. Edit or modify the DO declaration in a
corresponding example `runtime-init` configuration file with the new
values.

Example snippet:

From:
[source,yaml]
----
...
          My_System:
            autoPhonehome: true
            class: System
            hostname: "failover01.local"
...
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - failover01.local
              - failover02.local
...
----

To:
[source,yaml]
----
...
          My_System:
            autoPhonehome: false
            class: System
            hostname: "bigip-cluster-01-a.yourcompany.com"
...
          failoverGroup:
            class: DeviceGroup
            type: sync-failover
            members:
              - bigip-cluster-01-a.yourcompany.com
              - bigip-cluster-01-b.yourcompany.com
...
----


[arabic, start=2]
. Publish or host the customized `runtime-init` configuration files at a location
that can be accessed by {partner-product-short-name} at deployment time (for example, git, S3, etc.).
. Update the *bigIpRuntimeInitConfig* input parameters to reference the
new URLs of the updated configurations.

{empty} +
{empty} +


TIP: For additional information and examples, refer to the https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init^] GitHub repository.

{empty} +
{empty} +

=== Access the {partner-product-short-name} IP address


After the stacks show a *CREATE_COMPLETE* status, you can access the {partner-product-short-name} instances through the bastion host. If you've provisioned the example application, optionally test the WAF service:


* To access the parent template outputs, perform one of the following steps:
** If using the AWS Management Console, navigate to *CloudFormation > _<STACK_NAME>_ > Outputs*.
** If using the AWS Command Line Interface (AWS CLI), run this command:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME}  --query  "Stacks[0].Outputs"
----
** To obtain the private IP address of the {partner-product-short-name} management port, perform one of the following steps:
*** If using the AWS Management Console, navigate to *CloudFormation > _STACK_NAME_ > Outputs >
_bigipInstance01MgmtPrivateIp_*.
*** If using the AWS CLI, run this command:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[ OutputKey=='bigipInstance01MgmtPrivateIp'].OutputValue" --output text
----
** To obtain the public IP address of the bastion host, perform one of the following steps:
*** If using the AWS Management Console, navigate to *CloudFormation > _<STACK_NAME>_ > Outputs > _<bastionHost>_*.
*** If using the AWS CLI, run this command:
+
----
aws --region ${REGION} cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[ OutputKey=='bastionHost'].OutputValue" --output text
----


==== SSH

From your desktop client/shell, run this command to create an SSH tunnel. Replace the variables in brackets before running the command.
----
ssh -i [keyname-passed-to-template.pem] -o ProxyCommand='ssh -i [keyname-passed-to-template.pem] -W %h:%p ec2-user@[BASTION-HOST-PUBLIC-IP]' admin@[BIG-IP-MGMT-PRIVATE-IP]
----

Example:
----
ssh -i ~/.ssh/mykey.pem -o ProxyCommand=`ssh -i ~/.ssh/mykey.pem -W %h:%p ec2-user@34.82.102.190' admin@10.0.1.11
----

==== SSH and Configuration Utility (WebUI)

To obtain the URL address of the {partner-product-short-name} management port, perform the following steps:

NOTE: Multi-NIC environments use https://host, and single NIC environments use
https://host:8443.

. From your desktop client/shell, run this command to create an SSH tunnel through the bastion host:
+
----
ssh -i [keyname-passed-to-template.pem] ec2-user@[BASTION-HOST-PUBLIC-IP] -L [DESKTOP_PORT]:[BIG-IP-MGMT-PRIVATE-IP]:[BIGIP-GUI-PORT]
----
+
Example:
+
----
ssh -i ~/.ssh/mykey.pem ec2-user@34.82.102.190 -L 8443:10.0.1.11:443
----

. In a browser, navigate to the {partner-product-short-name} user interface:
+
https://localhost:8443

NOTE: By default, the {partner-product-short-name} system’s WebUI starts with a self-signed
certificate. Follow your browser’s instructions for accepting self-signed certificates
For example, if using Firefox, select *Advanced > Accept Risk and Continue*. If using Chrome, click inside the page and type *thisisunsafe*.

Login credentials
* username: admin
* password: _<YOUR_AWS_SECRET>_


=== Additional exploration

==== SSH

* From TMOS Shell (tmsh), type *bash* and then press the Enter key to access the bash shell.
** Examine the {partner-product-short-name} configuration file downloaded:
+
----
cat /config/cloud/runtime-init.conf
----
** Examine the running {partner-product-short-name} configurations:
*** https://www.f5.com/pdf/products/automation-toolchain-overview.pdf[F5
Automation Toolchain^] declarations include:
+
[source,bash]
----
curl -su admin: http://localhost:8100/mgmt/shared/declarative-onboarding | jq .
curl -su admin: http://localhost:8100/mgmt/shared/appsvcs/declare | jq .
----
*** https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud
Failover Extension^] declaration includes:
+
[source,bash]
----
curl -su admin: http://localhost:8100/mgmt/shared/cloud-failover/declare | jq .
----

==== WebUI

. If you provisioned the example application, navigate to *Virtual Services*.
. From the *Partition* menu in the upper-right corner of the screen, select *Partition =
`Tenant_1`*.
. Navigate to *Local Traffic > Virtual Servers*. You should see the virtual services for HTTP and HTTPS, with both appearing as green. Select them to look at the configuration that is declared in the
AS3 declaration.

. Navigate to *Security > Application Security*, and select the *CustomWAFPolicy* policy so you can inspect it.


=== Test the WAF service

If you've provisioned the example application, perform the following steps to test the WAF service:

[arabic]
. T obtain the address of the WAF service, perform one of the following steps:

* If using the AWS Management Console, navigate to *CloudFormation > _<STACK_NAME>_ > Outputs > _applicationPublicIp_*.
* If using the AWS CLI, run this command:
+
----
aws --region ${REGION}  cloudformation describe-stacks --stack-name ${STACK_NAME} --query  "Stacks[0].Outputs[?OutputKey=='applicationPublicIp'].OutputValue" --output text
----

[arabic, start=2]
. To verify that the application is responding:

* Paste the IP address in a browser: `https://${IP_ADDRESS_FROM_OUTPUT}`

NOTE: By default, the virtual service starts with a self-signed
certificate. Follow your browser’s instructions for accepting self-signed certificates
For example, if using Firefox, select *Advanced > Accept Risk and Continue*. If using Chrome, click inside the page and type *thisisunsafe*.

* To use CURL:
+
----
curl -sko /dev/null -w '%{response_code}\n' https://${IP_ADDRESS_FROM_OUTPUT}
----

[arabic, start=3]
. Verify the WAF is configured to block illegal requests:
+
----
curl -sk -X DELETE https://${IP_ADDRESS_FROM_OUTPUT}
----

* The response should include a message that the request was blocked and a reference support ID, for example:
+
----
$ curl -sko /dev/null -w '%{response_code}\n' https://55.55.55.55
200
$ curl -sk -X DELETE https://55.55.55.55
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected.
Please consult with your administrator.<br><br>Your support ID is:
2394594827598561347<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
----


=== Test the failover

If you have deployed the example application, perform the following steps to test the failover:

[arabic]
. Log in to the {partner-product-short-name} instances.
. Perform on the following steps:

* If using the AWS Management Console, navigate to *Device Management of Active Instance > Traffic-Groups*, and select the box next to *traffic-group-1*. Then select *Force to Standby*.
* If using the {partner-product-short-name} command line, run this command:
+
----
tmsh run sys failover standby
----

[arabic, start=2]
. Verify that the Elastic IP address associated with the virtual service (applicationPublicIp) is remapped to the peer {partner-product-short-name} instance (for example, from 10.0.10.11 in Availability Zone 1 to 10.0.20.11 in Availability Zone 2).


[arabic, start=2]
. To verify that the application is responding:

* Paste the IP address in a browser: `https://${IP_ADDRESS_FROM_OUTPUT}`

NOTE: By default, the virtual service starts with a self-signed
certificate. Follow your browser’s instructions for accepting self-signed certificates
For example, if using Firefox, select *Advanced > Accept Risk and Continue*. If using Chrome, click inside the page and type *thisisunsafe*.

* Use CURL:
+
----
curl -sko /dev/null -w '%{response_code}\n' https://${IP_ADDRESS_FROM_OUTPUT}
----

[arabic, start=3]
. Verify the WAF is configured to block illegal requests:
+
----
curl -sk -X DELETE https://${IP_ADDRESS_FROM_OUTPUT}
----

NOTE: In this example, traffic uses Source Network Address Translation (SNAT). According to the example application, the client is the SNAT address. The real client IP is passed via the `x-forwarded-for:` header. Observe how the client IP address changes from one {partner-product-short-name} instance in one Availability Zone to the other.


== Best practices for using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

// _Add any best practices for using the software._

For illustration purposes, this Quick Start provides an option to pre-provision additional cloud resources (IP addresses)
needed for an example virtual service. However, in practice, it's designed solely to facilitate the initial deployment as cloud-init runs once. It's  typically used for initial provisioning, not as the primary configuration API for a
long-running platform. More typically in an infrastructure use case,
virtual services are added after initial deployment, outside the lifecycle of this Cloudformation template. 

=== Add services via the cloud
Provision additional IP addresses on the desired network interfaces. Refer to the following resources:
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/MultipleIP.html#ManageMultipleIP[Assign a secondary private IPv4 address^]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-allocating[Allocate an Elastic IP address^]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-associating[Associate an Elastic IP address with an instance or network interface^]

=== Add services via {partner-product-short-name}
Create virtual services that match the secondary IP addresses. Also update the AS3 declaration with additional virtual services. Refer to https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/composing-a-declaration.html[Composing an AS3 Declaration] for more information.  


NOTE: For cloud resources, templates can be created or customized to pre-provision
and update addtional resources (for example, various combinations of
NICs, IPs, public IPs, etc). Refer to the link:#_support[Support] section
for more information. For the {partner-product-short-name} configurations, use either REST or Automation Toolchain clients like
https://ansible.github.io/workshops/exercises/ansible_f5/3.0-as3-intro/[Ansible^] or https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_as3[Terraform^]. 

== Delete the deployment

Cloudformation doesn't delete S3 buckets that contain data. To delete this deployment, manually empty and/or delete the S3 bucket created for the Cloud Failover Extension (provided via the *cfeS3Bucket* parameter). In the AWS Management Console, go to S3 and search for the *cfeS3Bucket* bucket name. Select the radio button associated with the bucket and select *Empty*.

You can now delete the deployment. Still in the AWS Management Console, open Cloudformation, go to *Stacks*, and select the radio button associated with the parent stack. Finally, select *Empty*.

For more information, refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^].


== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.


This solution requires internet access for:

[arabic]
. Downloading additional F5 software components used for onboarding and
configuring the {partner-product-short-name} instance (via GitHub.com). Internet access is required via
the management interface and then via a dataplane interface (for
example, external Self-IP) once a default route is configured. Refer to
https://support.f5.com/csp/article/K13284[Overview of management interface routing^] for
more details. By default, as a convenience, this Quick Start provisions
public IP addresses to enable this, but in a production environment, outbound
access should be provided by a `routed` SNAT service (for example, NAT
gateway, custom firewall, etc). 

NOTE: Access via web proxy is not
currently supported. Other options include either:
* Hosting the file locally
and modifying the runtime-init package URL and configuration files to
point to local URLs instead.
* Baking them into a custom image, using
the https://clouddocs.f5.com/cloud/public/v1/ve-image-gen_index.html[F5 BIG-IP Image Generation Tool^].

. Contacting native cloud services (for example, s3.amazonaws.com,
ec2.amazonaws.com, etc.) for various cloud integrations, including: 

=== Onboarding
** https://github.com/f5networks/f5-bigip-runtime-init[F5 BIG-IP Runtime
Init] to fetch secrets from native vault services 

=== Operation
** https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/[F5 Application Services 3^] for features like Service Discovery
** https://clouddocs.f5.com/products/extensions/f5-telemetry-streaming/latest/[F5 Telemetry Streaming^] for logging and reporting
** https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud Failover Extension^] for updating IP addresses and route mappings
** You can use additional cloud services like https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints.html[VPC endpoints^] to address calls to native services traversing the Internet. See the link:#_security[Security] section for more details.

The Quick Start's CloudFormation template downloads helper code to configure the
{partner-product-short-name} system:

* f5-bigip-runtime-init.gz.run: The self-extracting installer for the F5
BIG-IP Runtime Init RPM can be verified against a SHA256 checksum
provided as a release asset on the F5 BIG-IP Runtime Init public GitHub
repository, for example:
https://github.com/F5Networks/f5-bigip-runtime-init/releases/download/1.4.1/f5-bigip-runtime-init-1.4.1-1.gz.run.sha256.
* F5 BIG-IP Runtime Init: The self-extracting installer script extracts,
verifies, and installs the F5 BIG-IP Runtime Init RPM package. Package
files are signed by F5 and automatically verified using GPG.
* F5 Automation Toolchain components: F5 BIG-IP Runtime Init downloads,
installs, and configures the F5 Automation Toolchain components.
Although optional, F5 recommends adding the extensionHash field to
each extension install operation in the configuration file. This field triggers verification of the downloaded component package
checksum against the provided value. The checksum values are published
as release assets on each extension’s public GitHub repository, for
example:
https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.30.0/f5-appsvcs-3.30.0-5.noarch.rpm.sha256

The following configuration file verifies the DO
and application services extensions before configuring AS3 from a local
file:

[source,yaml]
----
runtime_parameters: []
extension_packages:
    install_operations:
        - extensionType: do
          extensionVersion: 1.23.0
          extensionHash: bfe88c7cf3fdb24adc4070590c27488e203351fc808d57ae6bbb79b615d66d27
        - extensionType: as3
          extensionVersion: 3.30.0
          extensionHash: 47cc7bb6962caf356716e7596448336302d1d977715b6147a74a142dc43b391b
extension_services:
    service_operations:
      - extensionType: as3
        type: url
        value: file:///examples/declarations/as3.json
----

For more information about F5 BIG-IP Runtime Init and additional examples, refer to the https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/README.md[GitHub repository^].


This template can send non-identifiable statistical information to F5 to help improve templates. You can disable this functionality by setting the **autoPhonehome** system class property value to false in the F5 DO declaration. See information about customizing the {partner-product-short-name} configuration earlier in this guide.

{partner-product-short-name} may contact the following list of endpoints during onboarding:

* {partner-product-short-name} image default:
** vector2.brightcloud.com (by {partner-product-short-name} image for
https://support.f5.com/csp/article/K03011490[IPI subscription validation^])

* Solution/onboarding:
** github.com (for downloading helper packages mentioned earlier)
** f5-cft.s3.amazonaws.com (downloading GPG Key and other helper configuration files)
** license.f5.com (licensing functions)

* Telemetry:

** product-s.apis.f5.com.
** f5-prod-webdev-prod.apigee.net.
** id-prod-global-endpoint.trafficmanager.net.
** global.azure-devices-provisioning.net.
** www-google-analytics.l.google.com


