// Add any unique troubleshooting steps here.

== Troubleshooting

For troubleshooting common Quick Start issues, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

// == Resources
// Uncomment section and add links to any external resources that are specified by the partner
There are generally two classes of issues:

. Stack creation itself failed
. Resource(s) within the stack failed to deploy

In the event that a template in the stack failed, click on the name of a failed stack and then click `Events`. Check the `Status Reason` column for the failed event for details about the cause.

**When creating a GitHub issue for a template, please include as much information as possible from the failed CloudFormation stack events.**

Common deployment failure causes include:

- Required fields were left empty or contained incorrect values (input type mismatch, prohibited characters, etc) causing template validation failure
- Insufficient permissions to create the deployment or resources created by a deployment (IAM roles, etc). See link:#_technical_requirements[Technical requirements].
- Resource limitations (exceeded limit of IP addresses or compute resources, etc). See link:#_technical_requirements[Technical requirements].
- AWS service issues (service health can be checked from the https://status.aws.amazon.com/[AWS Service Health Dashboard]

If all stacks were created "successfully" but maybe the BIG-IP or Service is not reachable, then log in to the BIG-IP instance via SSH to confirm the BIG-IP deployment or desired configuration was successful (for example, if startup scripts completed as expected on the BIG-IP). To verify BIG-IP deployment, perform the following steps:

- Obtain the IP address of the BIG-IP instance. See instructions for link:#_accessing_the_big_ip[Accessing the BIG-IP].
- Check startup-script to make sure was installed/interpolated correctly:
  * ```cat /opt/cloud/instance/user-data.txt```
- Check the logs (in order of invocation):
  * cloud-init Logs:
    ** */var/log/boot.log*
    ** */var/log/cloud-init.log*
    ** */var/log/cloud-init-output.log*
  * runtime-init Logs:
    ** */var/log/cloud/startup-script.log*: This file contains events that happen prior to execution of f5-bigip-runtime-init. If the files required by the deployment fail to download, for example, you will see those events logged here.
    ** */var/log/cloud/bigipRuntimeInit.log*: This file contains events logged by the f5-bigip-runtime-init onboarding utility. If the configuration is invalid causing onboarding to fail, you will see those events logged here. If deployment is successful, you will see an event with the body "All operations completed successfully".
  * Automation Tool Chain Logs:
    ** */var/log/restnoded/restnoded.log*: This file contains events logged by the F5 Automation Toolchain components. If an Automation Toolchain declaration fails to deploy, you will see more details for those events logged here.

**GENERAL LOG TIP**: Search most critical error level errors first (for example, egrep -i err /var/log/<Logname>).

If you are unable to login to the BIG-IP instance, you can navigate to **EC2 > Instances**, select the check box next to the instance you want to troubleshoot, and then click **Actions > Monitor and Troubleshoot > Get System Log** or **Get Instance Screenshot** for potential logging to serial console.

[source,shell]
----
aws ec2 get-console-output --region ${REGION}  --instance-id <ID>
----

== Support

Due to the heavy customization requirements of external cloud resources and BIG-IP configurations in these solutions, F5 does not provide technical support for deploying, customizing, or troubleshooting the templates themselves. However, the various underlying products and components used (for example: https://clouddocs.f5.com/cloud/public/v1/[F5 BIG-IP Virtual Edition], https://github.com/F5Networks/f5-bigip-runtime-init[F5 BIG-IP Runtime Init], https://www.f5.com/pdf/products/automation-toolchain-overview.pdf[F5 Automation Toolchain] extensions, and https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/[Cloud Failover Extension (CFE)]) in the solutions located here are F5-Supported and capable of being deployed with other orchestration tools. Read more about https://www.f5.com/company/policies/support-policies[Support Policies]. Problems found with the templates deployed as-is should be reported via a GitHub issue.

For help with authoring and support for custom templates, we recommend engaging https://www.f5.com/services/professional-services[F5 Professional Services (PS)].
